services:
  db:
    image: postgres:16.4-alpine3.20
    restart: always
    environment:
      POSTGRES_DB: tur_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    image: touristapp
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tur_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db

volumes:
  db-data: